FROM node:18-alpine

WORKDIR /app/gateway

COPY SERVICE.json RESPONSE.json EXCHANGE.json ACTION.json /app/

COPY gateway/package.json .

RUN npm install -g pnpm

RUN pnpm install 

# COPY gateway/ ./

# COPY gateway/src ./src

# COPY gateway/.env gateway/index.js gateway/server.js gateway/firebase.json ./

EXPOSE 8000

CMD ["pnpm", "dev"]