version: 2.1
jobs:
  client_test:
    docker:
      - image: cimg/node:18.18.2
    working_directory: ~/client
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: sudo npm install -g pnpm
      - restore_cache:
          key: client-dependencies-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install dependencies
          command: pnpm install
      - save_cache:
          key: client-dependencies-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: pnpm test
workflows:
  version: 2
  test_client:
    jobs:
      - client_test
