x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

name: judge0-1131
services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - vnoi-backend
      - judge0

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - judge0

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    networks:
      - judge0

  redis:
    image: redis:7.2.4
    command: ["bash", "-c", 'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"']
    env_file: judge0.conf
    <<: *default-logging
    restart: always
    networks:
      - judge0

volumes:
  data:

networks:
  judge0:
    driver: bridge
  vnoi-backend:
    driver: overlay
    external: true
