name: Continuous Integration With PNPM

on:
  push:
    branches: ['test']

permissions:
  checks: write
  contents: write
  pull-requests: write
  deployments: write

jobs:
  check-version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get-version
        run: |
          VERSION=$(jq -r ".version" ./server/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  
