name: Continuous Integration With PNPM

on:
  push:
    branches: ['test']

permissions:
  checks: write
  contents: write
  pull-requests: write
  deployments: write

jobs:
  get_version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(cat version)"
  get_image:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./server/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: |
          echo "Building image"
          docker build -t lehodev/vnoi-backend-learning:${{ github.sha }} ./learning
          docker build -t lehodev/vnoi-backend-statistics:${{ github.sha }} ./statistics
          docker build -t lehodev/vnoi-backend-logging:${{ github.sha }} ./logging

      - name: Push image
        run: |
          echo "Pushing image"
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push lehodev/vnoi-backend-learning:${{ github.sha }}
          docker push lehodev/vnoi-backend-statistics:${{ github.sha }}
          docker push lehodev/vnoi-backend-logging:${{ github.sha }}
