name: Continuous Integration With PNPM

on:
  push:
    branches: ['test']

permissions:
  checks: write
  contents: write
  pull-requests: write
  deployments: write

jobs:
  check-version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get-version
        run: |
          VERSION=$(jq -r ".version" ./server/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-and-push-image:
    runs-on: ubuntu-22.04
    needs: check-version
    defaults:
      run:
        working-directory: server
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        id: build
        run: |
          VERSION=${{ needs.check-version.outputs.version }} docker compose --no-env -f docker-compose.prod.yml build

      - name: Push image
        id: push
        run: |
          VERSION=${{ needs.check-version.outputs.version }} docker compose -f docker-compose.prod.yml push
