# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration With PNPM

on:
  push:
    branches: ['test']

permissions:
  checks: write
  contents: write
  deployments: write

jobs:
  staging_server:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: 'actions/checkout@v4'
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - id: compute-ssh
        uses: google-github-actions/ssh-compute@v1
        with:
          instance_name: server-1
          zone: asia-southeast1-a
          ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          command: 'echo Hello world'

      - id: 'test'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
