name: Continuous Integration With PNPM

on:
  push:
    branches: ['test']

permissions:
  checks: write
  contents: write
  pull-requests: write
  deployments: write

jobs:
  version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(cat version)"
